name: Commit and push changes
description: Setup and push changes
inputs:
  commit_message:
    description: The commit message for the push
    required: true
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Configure git for private modules
      shell: bash
      run: |
        git config --global user.email "ci@hostfactor.io"
        git config --global user.name "Host Factor CI"
        git config --global url."https://GITHUB_USER:${{inputs.github_token}}@github.com".insteadOf "https://github.com"
    - name: Commit changes
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "${{inputs.commit_message}}"
          git push
        else
          echo "No changes";
        fi
