name: Commit and push changes
description: Setup and push changes
inputs:
  commit_message:
    description: The commit message for the push
    required: true

runs:
  using: composite
  steps:
    - name: Commit changes
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "${{inputs.commit_message}}"
          git push
        else
          echo "No changes";
        fi
