name: terraria
author: https://github.com/eddieowens
description: A containerized terraria server hosted at hostfactor.io

features:
  - name: mobile
    context: mobile
    tags:
      - mobile-1.4.4.9
      - mobile-latest
    description: A containerized terraria server for mobile hosted at hostfactor.io
    build_args:
      TERRARIA_VERSION: "1449"
  - name: tshock
    context: tshock
    tags:
      - tshock-1.4.4.9
      - tshock-latest
    description: A containerized terraria server with TShock support hosted at hostfactor.io
    build_args:
      TERRARIA_VERSION: "1.4.4.9"
  - name: tmod
    context: tmod
    tags:
      - tmod-1.4.4.9
      - tmod-latest
    build_args:
      TERRARIA_VERSION: "1449"
      TMOD_VERSION: $GITHUB_RELEASE_TAG_NAME
    watch:
      github_release:
        repo: tModLoader/tModLoader
    description: A containerized terraria server with TMod support hosted at hostfactor.io
  - name: vanilla
    context: vanilla
    tags:
      - vanilla-1.4.4.9
      - vanilla-latest
    description: A containerized vanilla terraria server hosted at hostfactor.io
    build_args:
      TERRARIA_VERSION: "1449"
