name: terraria
author: https://github.com/eddieowens
description: A containerized terraria server hosted at hostfactor.io
builds:
  - name: mobile
    description: A containerized terraria server for mobile hosted at hostfactor.io
    spec:
      context: mobile
      tags:
        - mobile-1.4.4.9
        - mobile-latest
      build_args:
        TERRARIA_VERSION: "1449"
  - name: tshock
    description: A containerized terraria server with TShock support hosted at hostfactor.io
    spec:
      build_args:
        TERRARIA_VERSION: "1.4.4.9"
      context: tshock
      tags:
        - tshock-1.4.4.9
        - tshock-latest
  - name: tmod
    description: A containerized terraria server with TMod support hosted at hostfactor.io
    spec:
      context: tmod
      tags:
        - tmod-1.4.4.9
        - tmod-latest
      build_args:
        TERRARIA_VERSION: "1449"
        TMOD_VERSION: ${{ steps.github_release.outputs.tag_name }}
    watch:
      github_release:
        repo: tModLoader/tModLoader
  - name: vanilla
    description: A containerized vanilla terraria server hosted at hostfactor.io
    spec:
      context: vanilla
      tags:
        - vanilla-1.4.4.9
        - vanilla-latest
      build_args:
        TERRARIA_VERSION: "1449"
