name: palworld
author: https://github.com/eddieowens
description: A containerized palworld server hosted at hostfactor.io
builds:
- name: main
  spec:
    tags:
    - latest
    - ${{ env.LATEST_STEAM_VERSION }}
    build_args:
      VERSION: ${{ steps.version.outputs.version }}
  description: A containerized palworld server for hostfactor.io
  trigger:
    outputs:
      steam_news_version: 0.2.1.0
      created_at: 2024-04-05T03:30:29Z
    steam_feed:
      app_id: "1623730"
      spec:
        title_matcher: "v([\\.\\d]{3,})"
