name: palworld
author: https://github.com/eddieowens
description: A containerized palworld server hosted at hostfactor.io
builds:
- name: main
  spec:
    tags:
    - latest
    - ${{ env.LATEST_STEAM_VERSION }}
    build_args:
      VERSION: ${{ steps.version.outputs.version }}
  description: A containerized palworld server for hostfactor.io
  trigger:
    outputs:
      steam_news_version: 0.4.14
      created_at: 2025-01-24T03:13:02Z
      release_link: https://store.steampowered.com/news/app/1623730/view/544473335607591623
    steam_feed:
      app_id: "1623730"
      spec:
        title_matcher: "v([\\.\\d]{3,})"
