name: terraria
author: https://github.com/eddieowens
description: A containerized terraria server hosted at hostfactor.io
features:
  - name: mobile
    tag: 1.4.4.9
  - name: tshock
    tag: 1.4.4.9
  - name: tmod
    tag: 1.4.4.9
  - name: vanilla
    tag: 1.4.4.9
